#!/usr/bin/env python3
"""Interactive setup wizard — generates config.yaml on first run."""
import sys
from pathlib import Path

CONFIG_FILE = Path(__file__).parent / "config.yaml"
EXAMPLE_FILE = Path(__file__).parent / "config.yaml.example"


def ask(prompt, default=None, required=True):
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"{prompt}{suffix}: ").strip()
        if not val and default:
            return default
        if val:
            return val
        if not required:
            return ""
        print("  This field is required.")


def ask_yn(prompt, default=True):
    hint = "Y/n" if default else "y/N"
    val = input(f"{prompt} [{hint}]: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def run():
    print()
    print("=" * 50)
    print("  Frank — First-Time Setup")
    print("=" * 50)
    print()
    print("This wizard creates your config.yaml.")
    print("You can always edit it later.")
    print()

    # --- Matrix ---
    print("— Matrix Connection —")
    homeserver = ask("Matrix homeserver URL", "https://matrix.example.com")
    bot_user = ask("Bot username (e.g. @frank:your.server)")
    room_id = ask("Family room ID (e.g. !abc123:your.server)")
    bot_name = ask("Bot display name", "Frank")
    print()

    # --- Family ---
    print("— Family Members —")
    print("Add the owner (admin) first, then any other members.")
    print()

    members = {}
    owner_key = None

    while True:
        key = ask("Member key (short name, e.g. 'dave')" if not members else "Member key (or press Enter to finish)", required=not members)
        if not key:
            break
        matrix_id = ask(f"  {key}'s Matrix ID (e.g. @{key}:your.server)")
        nickname = ask(f"  {key}'s nickname (how Frank addresses them)")
        members[key] = {"matrix_id": matrix_id, "nickname": nickname}
        if not owner_key:
            owner_key = key
            print(f"  → {key} set as owner (admin)")
        print()

    # --- Location ---
    print("— Location (for weather/briefings) —")
    lat = ask("Latitude", "43.65")
    lon = ask("Longitude", "-79.38")
    tz = ask("Timezone", "America/New_York")
    print()

    # --- AI ---
    print("— AI Model —")
    print("Frank uses OpenRouter. Set OPENROUTER_API_KEY in your environment.")
    model = ask("AI model", "anthropic/claude-haiku-4.5")
    print()

    # --- Features ---
    print("— Optional Features —")
    print("Enable what you need. All can be changed later in config.yaml.")
    print()

    grocery = ask_yn("Grocery lists & inventory?", True)
    recipes = ask_yn("Recipe database?", True)
    buddy_pet = ask_yn("Companion pets (Tamagotchi)?", True)

    firefly_on = ask_yn("Firefly III (finance tracking)?", False)
    firefly_url = ""
    if firefly_on:
        firefly_url = ask("  Firefly III API URL", "http://localhost:8090/api/v1")

    email_on = ask_yn("Email (IMAP)?", False)
    imap_host = ""
    if email_on:
        imap_host = ask("  IMAP host")

    gmail_on = False
    if not email_on:
        gmail_on = ask_yn("Gmail (OAuth2)?", False)

    immich_on = ask_yn("Immich (photo search)?", False)
    immich_url = ""
    immich_key = ""
    immich_ssl = False
    if immich_on:
        immich_url = ask("  Immich API URL", "http://localhost:2283/api")
        immich_key = ask("  Immich API key")
        immich_ssl = ask_yn("  Skip SSL verification (self-signed cert)?", False)

    telegram_on = ask_yn("Telegram?", False)
    telegram_group = ""
    if telegram_on:
        telegram_group = ask("  Telegram family group ID", required=False)

    mem0_on = ask_yn("Mem0 memory (requires Ollama)?", False)
    web_search_on = ask_yn("Web search (requires Tavily)?", False)

    print()

    # --- Build config ---
    lines = [
        "# Frank Family Bot Configuration",
        "# Generated by setup wizard",
        "",
        "# --- Bot Identity ---",
        "bot:",
        f'  name: "{bot_name}"',
        f'  matrix_homeserver: "{homeserver}"',
        f'  matrix_bot_user: "{bot_user}"',
        f'  matrix_family_room_id: "{room_id}"',
        "",
        "# --- Family Members ---",
        "family:",
        f'  owner: "{owner_key}"',
        "  members:",
    ]

    for key, m in members.items():
        lines.append(f"    {key}:")
        lines.append(f'      matrix_id: "{m["matrix_id"]}"')
        lines.append(f'      nickname: "{m["nickname"]}"')

    lines += [
        "",
        "# --- Paths ---",
        "paths:",
        '  data_dir: "./data"',
        "",
        "# --- Location ---",
        "location:",
        f"  latitude: {lat}",
        f"  longitude: {lon}",
        f'  timezone: "{tz}"',
        "",
        "# --- Built-in Features ---",
        "grocery:",
        f"  enabled: {str(grocery).lower()}",
        "recipes:",
        f"  enabled: {str(recipes).lower()}",
        "buddy:",
        f"  enabled: {str(buddy_pet).lower()}",
        "",
        "# --- AI ---",
        "ai:",
        f'  model: "{model}"',
    ]

    # Telegram
    lines += [
        "",
        "# --- Telegram ---",
        "telegram:",
        f"  enabled: {str(telegram_on).lower()}",
    ]
    if telegram_group:
        lines.append(f'  family_group_id: "{telegram_group}"')

    # Firefly
    lines += [
        "",
        "# --- Firefly III ---",
        "firefly:",
        f"  enabled: {str(firefly_on).lower()}",
    ]
    if firefly_url:
        lines.append(f'  base_url: "{firefly_url}"')
        lines += [
            "  accounts:",
            "    chequing: 1",
            "    savings: 2",
            "    credit_card: 3",
        ]

    # Email
    lines += [
        "",
        "# --- Email (IMAP) ---",
        "email:",
        f"  enabled: {str(email_on).lower()}",
    ]
    if imap_host:
        lines += [
            f'  imap_host: "{imap_host}"',
            "  imap_port: 993",
            f'  smtp_host: "{imap_host}"',
            "  smtp_port: 587",
        ]

    # Gmail
    lines += [
        "",
        "# --- Gmail ---",
        "gmail:",
        f"  enabled: {str(gmail_on).lower()}",
    ]

    # Immich
    lines += [
        "",
        "# --- Immich ---",
        "immich:",
        f"  enabled: {str(immich_on).lower()}",
    ]
    if immich_url:
        lines.append(f'  base_url: "{immich_url}"')
        lines.append(f'  api_key: "{immich_key}"')
        lines.append(f"  skip_ssl_verify: {str(immich_ssl).lower()}")

    # Mem0
    lines += [
        "",
        "# --- Mem0 Memory ---",
        "mem0:",
        f"  enabled: {str(mem0_on).lower()}",
    ]
    if mem0_on:
        lines += [
            '  ollama_base_url: "http://localhost:11434"',
            '  ollama_model: "nomic-embed-text"',
        ]

    # Web search
    lines += [
        "",
        "# --- Web Search ---",
        "web_search:",
        f"  enabled: {str(web_search_on).lower()}",
    ]

    # Voice, briefing, persona defaults
    lines += [
        "",
        "# --- Voice API ---",
        "voice:",
        "  enabled: false",
        "",
        "# --- Briefing ---",
        "briefing:",
        "  commutes: {}",
        "",
        "# --- Persona ---",
        "persona_file: null",
        "spanish_learners: []",
        "",
    ]

    config_text = "\n".join(lines)
    CONFIG_FILE.write_text(config_text)

    print("=" * 50)
    print(f"  config.yaml created!")
    print("=" * 50)
    print()

    # --- Env var checklist ---
    env_vars = [("MATRIX_BOT_PASSWORD", True), ("OPENROUTER_API_KEY", True)]
    if firefly_on:
        env_vars.append(("FIREFLY_TOKEN", True))
    if email_on:
        env_vars += [("EMAIL_USER", True), ("EMAIL_PASS", True)]
    if telegram_on:
        env_vars.append(("TELEGRAM_BOT_TOKEN", True))
    if web_search_on:
        env_vars.append(("TAVILY_API_KEY", True))

    print("Environment variables you still need to set:")
    print()
    for var, _ in env_vars:
        print(f"  export {var}=...")
    print()
    print("Add these to a .env file or export them before running Frank.")
    print()
    print("Start Frank with:  python matrix_bot.py")
    print()


if __name__ == "__main__":
    if CONFIG_FILE.exists():
        print(f"config.yaml already exists. Delete it first to re-run setup.")
        sys.exit(1)
    run()
